# Generated by Django 5.2.7 on 2025-11-05 13:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(blank=True, max_length=200)),
                ('site', models.URLField(blank=True, max_length=300)),
                ('date_played', models.DateField()),
                ('result', models.CharField(choices=[('1-0', 'White wins'), ('0-1', 'Black wins'), ('1/2-1/2', 'Draw'), ('*', 'Unknown/Ongoing')], max_length=10)),
                ('white_rating', models.IntegerField(blank=True, null=True)),
                ('black_rating', models.IntegerField(blank=True, null=True)),
                ('time_control', models.CharField(max_length=50)),
                ('opening_name', models.CharField(blank=True, max_length=200)),
                ('eco_code', models.CharField(blank=True, max_length=10)),
                ('eco_url', models.URLField(blank=True, max_length=300)),
                ('termination', models.CharField(blank=True, max_length=100)),
                ('total_moves', models.IntegerField(default=0)),
                ('pgn_raw', models.TextField()),
                ('link', models.URLField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date_played', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GameSummary',
            fields=[
                ('game', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='summary', serialize=False, to='chess.game')),
                ('accuracy_white', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('accuracy_black', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('avg_time_per_move_white', models.FloatField(blank=True, null=True)),
                ('avg_time_per_move_black', models.FloatField(blank=True, null=True)),
                ('blunders_white', models.IntegerField(default=0)),
                ('blunders_black', models.IntegerField(default=0)),
                ('mistakes_white', models.IntegerField(default=0)),
                ('mistakes_black', models.IntegerField(default=0)),
                ('inaccuracies_white', models.IntegerField(default=0)),
                ('inaccuracies_black', models.IntegerField(default=0)),
                ('avg_centipawn_loss_white', models.FloatField(blank=True, null=True)),
                ('avg_centipawn_loss_black', models.FloatField(blank=True, null=True)),
                ('opening_moves', models.IntegerField(default=0)),
                ('middlegame_moves', models.IntegerField(default=0)),
                ('endgame_moves', models.IntegerField(default=0)),
                ('white_in_time_trouble', models.BooleanField(default=False)),
                ('black_in_time_trouble', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('platform', models.CharField(default='chess.com', max_length=50)),
                ('country', models.CharField(blank=True, max_length=3, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['username', 'platform'], name='chess_playe_usernam_dff2a2_idx')],
                'unique_together': {('username', 'platform')},
            },
        ),
        migrations.AddField(
            model_name='game',
            name='black_player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games_as_black', to='chess.player'),
        ),
        migrations.AddField(
            model_name='game',
            name='white_player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games_as_white', to='chess.player'),
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('move_number', models.IntegerField()),
                ('color', models.CharField(choices=[('white', 'White'), ('black', 'Black')], max_length=5)),
                ('move_notation', models.CharField(max_length=20)),
                ('clock_time_remaining', models.IntegerField(blank=True, help_text='Seconds remaining on clock after this move', null=True)),
                ('time_spent', models.IntegerField(blank=True, help_text='Seconds spent thinking about this move', null=True)),
                ('fen_before', models.CharField(blank=True, max_length=100)),
                ('fen_after', models.CharField(blank=True, max_length=100)),
                ('evaluation', models.FloatField(blank=True, help_text='Centipawn evaluation (positive = white advantage)', null=True)),
                ('best_move', models.CharField(blank=True, max_length=20)),
                ('is_blunder', models.BooleanField(default=False)),
                ('is_mistake', models.BooleanField(default=False)),
                ('is_inaccuracy', models.BooleanField(default=False)),
                ('is_brilliant', models.BooleanField(default=False)),
                ('is_best', models.BooleanField(default=False)),
                ('centipawn_loss', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moves', to='chess.game')),
            ],
            options={
                'ordering': ['game', 'move_number', 'color'],
                'indexes': [models.Index(fields=['game', 'move_number'], name='chess_move_game_id_35beda_idx'), models.Index(fields=['is_blunder'], name='chess_move_is_blun_077d74_idx'), models.Index(fields=['is_mistake'], name='chess_move_is_mist_a73d3b_idx')],
                'unique_together': {('game', 'move_number', 'color')},
            },
        ),
        migrations.CreateModel(
            name='Opening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_name', models.CharField(max_length=200)),
                ('eco_code', models.CharField(blank=True, max_length=10)),
                ('games_played', models.IntegerField(default=0)),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('draws', models.IntegerField(default=0)),
                ('games_as_white', models.IntegerField(default=0)),
                ('games_as_black', models.IntegerField(default=0)),
                ('avg_accuracy', models.FloatField(blank=True, null=True)),
                ('avg_centipawn_loss', models.FloatField(blank=True, null=True)),
                ('avg_game_length', models.FloatField(blank=True, null=True)),
                ('last_played', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opening_stats', to='chess.player')),
            ],
            options={
                'indexes': [models.Index(fields=['player', 'opening_name'], name='chess_openi_player__c8f522_idx'), models.Index(fields=['eco_code'], name='chess_openi_eco_cod_3f363e_idx')],
                'unique_together': {('player', 'opening_name')},
            },
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['white_player', 'date_played'], name='chess_game_white_p_7a3cf7_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['black_player', 'date_played'], name='chess_game_black_p_130c98_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['date_played'], name='chess_game_date_pl_3916c2_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['result'], name='chess_game_result_256ece_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['opening_name'], name='chess_game_opening_f8eb1a_idx'),
        ),
    ]
